# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 463)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Eml_lbl = QtWidgets.QLabel(self.centralwidget)
        self.Eml_lbl.setGeometry(QtCore.QRect(150, 110, 61, 16))
        self.Eml_lbl.setObjectName("Eml_lbl")
        self.Eml_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.Eml_lbl_2.setGeometry(QtCore.QRect(154, 190, 71, 20))
        self.Eml_lbl_2.setObjectName("Eml_lbl_2")
        self.Button01 = QtWidgets.QPushButton(self.centralwidget)
        self.Button01.setGeometry(QtCore.QRect(220, 260, 93, 28))
        self.Button01.setObjectName("Button01")
        self.Button02 = QtWidgets.QPushButton(self.centralwidget)
        self.Button02.setGeometry(QtCore.QRect(350, 260, 93, 28))
        self.Button02.setObjectName("Button02")
        self.Email_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.Email_txt.setGeometry(QtCore.QRect(240, 110, 181, 22))
        self.Email_txt.setObjectName("Email_txt")
        self.Pwd_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.Pwd_txt.setGeometry(QtCore.QRect(240, 190, 181, 22))
        self.Pwd_txt.setText("")
        self.Pwd_txt.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pwd_txt.setObjectName("Pwd_txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Button02.clicked.connect(self.Email_txt.clear) # type: ignore
        self.Button02.clicked.connect(self.Pwd_txt.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Eml_lbl.setText(_translate("MainWindow", "Email"))
        self.Eml_lbl_2.setText(_translate("MainWindow", "Password"))
        self.Button01.setText(_translate("MainWindow", "Ok"))
        self.Button02.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
