# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qlineedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(727, 481)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 40, 101, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 210, 91, 16))
        self.label_5.setObjectName("label_5")
        self.t1 = QtWidgets.QLineEdit(Form)
        self.t1.setGeometry(QtCore.QRect(180, 40, 113, 22))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(Form)
        self.t2.setGeometry(QtCore.QRect(180, 100, 113, 22))
        self.t2.setObjectName("t2")
        self.t3 = QtWidgets.QLineEdit(Form)
        self.t3.setGeometry(QtCore.QRect(180, 150, 113, 22))
        self.t3.setText("")
        self.t3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QLineEdit(Form)
        self.t4.setGeometry(QtCore.QRect(180, 210, 113, 22))
        self.t4.setObjectName("t4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Integer Validator"))
        self.label_3.setText(_translate("Form", "Input Mask"))
        self.label_4.setText(_translate("Form", "Password Field"))
        self.label_5.setText(_translate("Form", "Text Changed"))
        self.t2.setInputMask(_translate("Form", "+99 999 999 9999"))
        self.t2.setText(_translate("Form", "+ 91  "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
