# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import math
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def menufunction(self,action):
        txt=(action.text())
        no=int(self.t1.text())
        if(txt=="Square"):
            self.lineEdit_2.setText(str(no*no))
        if(txt=="Cube"):
            self.lineEdit_2.setText(str(no*no*no))
        if(txt=="SqrRoot"):
            self.lineEdit_2.setText(str(math.sqrt(no)))
        if(txt=="CubeRoot"):
            self.lineEdit_2.setText(str(math.pow(no,1/3)))
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 190, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(160, 90, 113, 22))
        self.t1.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.t1.setObjectName("t1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 190, 113, 22))
        self.lineEdit_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSquare = QtWidgets.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionCube = QtWidgets.QAction(MainWindow)
        self.actionCube.setObjectName("actionCube")
        self.actionSqrRoot = QtWidgets.QAction(MainWindow)
        self.actionSqrRoot.setObjectName("actionSqrRoot")
        self.actionCubeRoot = QtWidgets.QAction(MainWindow)
        self.actionCubeRoot.setObjectName("actionCubeRoot")
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSquare)
        self.menuOptions.addAction(self.actionCube)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSqrRoot)
        self.menuOptions.addAction(self.actionCubeRoot)
        self.menuOptions.addSeparator()
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menuOptions.triggered.connect(self.menufunction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Number"))
        self.label_2.setText(_translate("MainWindow", "Result"))
        self.menuOptions.setTitle(_translate("MainWindow", "Operations"))
        self.actionSquare.setText(_translate("MainWindow", "Square"))
        self.actionCube.setText(_translate("MainWindow", "Cube"))
        self.actionSqrRoot.setText(_translate("MainWindow", "SqrRoot"))
        self.actionCubeRoot.setText(_translate("MainWindow", "CubeRoot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
